// generated by tools/gen_tags.py — 手編集禁止。再生成一致オラクル: --verify
// 正本: src/dom.c の IF_TAGS（dom.h の IfTag 列挙と 1:1）
#![allow(missing_docs)] // 生成定数は個別 doc を付けない（名前が自己説明的）

/// flags ビット（C の F_VOID/F_RAW/F_RCDATA 相当）。
/// `F_VOID` = void 要素（閉じタグ不要）。
pub const F_VOID: u8 = 1;
/// `F_RAW` = rawtext 要素（文字参照を解釈しない）。
pub const F_RAW: u8 = 2;
/// `F_RCDATA` = rcdata 要素（`<title>` 等）。
pub const F_RCDATA: u8 = 4;

/// (canonical lowercase name, flags) の表。index 0 = UNKNOWN（空名）。
/// name 長は `str.len()` から導出（C の手書き n フィールドは不要）。
pub const TAGS: &[(&str, u8)] = &[
    ("", 0),
    ("html", 0),
    ("head", 0),
    ("body", 0),
    ("title", 4),
    ("meta", 1),
    ("link", 1),
    ("style", 2),
    ("script", 2),
    ("div", 0),
    ("span", 0),
    ("p", 0),
    ("a", 0),
    ("b", 0),
    ("i", 0),
    ("u", 0),
    ("s", 0),
    ("em", 0),
    ("strong", 0),
    ("code", 0),
    ("pre", 0),
    ("blockquote", 0),
    ("h1", 0),
    ("h2", 0),
    ("h3", 0),
    ("h4", 0),
    ("h5", 0),
    ("h6", 0),
    ("ul", 0),
    ("ol", 0),
    ("li", 0),
    ("dl", 0),
    ("dt", 0),
    ("dd", 0),
    ("table", 0),
    ("thead", 0),
    ("tbody", 0),
    ("tfoot", 0),
    ("tr", 0),
    ("td", 0),
    ("th", 0),
    ("caption", 0),
    ("img", 1),
    ("br", 1),
    ("hr", 1),
    ("form", 0),
    ("input", 1),
    ("button", 0),
    ("select", 0),
    ("option", 0),
    ("label", 0),
    ("textarea", 4),
    ("header", 0),
    ("footer", 0),
    ("nav", 0),
    ("main", 0),
    ("section", 0),
    ("article", 0),
    ("aside", 0),
    ("figure", 0),
    ("figcaption", 0),
    ("address", 0),
    ("small", 0),
    ("big", 0),
    ("sub", 0),
    ("sup", 0),
    ("mark", 0),
    ("time", 0),
    ("q", 0),
    ("cite", 0),
    ("abbr", 0),
    ("dfn", 0),
    ("kbd", 0),
    ("samp", 0),
    ("var", 0),
    ("font", 0),
    ("center", 0),
    ("strike", 0),
    ("tt", 0),
    ("wbr", 1),
    ("noscript", 0),
    ("iframe", 2),
    ("object", 0),
    ("param", 1),
    ("source", 1),
    ("track", 1),
    ("video", 0),
    ("audio", 0),
    ("canvas", 0),
    ("svg", 0),
    ("math", 0),
    ("mi", 0),
    ("mo", 0),
    ("mn", 0),
    ("ms", 0),
    ("mtext", 0),
    ("annotation-xml", 0),
    ("foreignobject", 0),
    ("desc", 0),
    ("mglyph", 0),
    ("malignmark", 0),
    ("listing", 0),
    ("plaintext", 0),
    ("xmp", 2),
    ("noembed", 2),
    ("noframes", 2),
    ("ruby", 0),
    ("rp", 0),
    ("rt", 0),
    ("rtc", 0),
    ("rb", 0),
    ("frameset", 0),
    ("frame", 1),
    ("optgroup", 0),
    ("legend", 0),
    ("fieldset", 0),
    ("base", 1),
    ("col", 1),
    ("colgroup", 0),
    ("area", 1),
    ("map", 0),
    ("embed", 1),
    ("dir", 0),
    ("menu", 0),
    ("applet", 0),
    ("marquee", 0),
    ("basefont", 1),
    ("keygen", 1),
    ("template", 0),
    ("nobr", 0),
    ("details", 0),
    ("dialog", 0),
    ("hgroup", 0),
    ("search", 0),
    ("summary", 0),
    ("bgsound", 1),
    ("image", 0),
];

/// 各タグの ID 定数（match パターン用。name を大文字 + '-'→'_' に変換）。
pub const TAG_UNKNOWN: crate::tags::Tag = 0;
pub const TAG_HTML: crate::tags::Tag = 1;
pub const TAG_HEAD: crate::tags::Tag = 2;
pub const TAG_BODY: crate::tags::Tag = 3;
pub const TAG_TITLE: crate::tags::Tag = 4;
pub const TAG_META: crate::tags::Tag = 5;
pub const TAG_LINK: crate::tags::Tag = 6;
pub const TAG_STYLE: crate::tags::Tag = 7;
pub const TAG_SCRIPT: crate::tags::Tag = 8;
pub const TAG_DIV: crate::tags::Tag = 9;
pub const TAG_SPAN: crate::tags::Tag = 10;
pub const TAG_P: crate::tags::Tag = 11;
pub const TAG_A: crate::tags::Tag = 12;
pub const TAG_B: crate::tags::Tag = 13;
pub const TAG_I: crate::tags::Tag = 14;
pub const TAG_U: crate::tags::Tag = 15;
pub const TAG_S: crate::tags::Tag = 16;
pub const TAG_EM: crate::tags::Tag = 17;
pub const TAG_STRONG: crate::tags::Tag = 18;
pub const TAG_CODE: crate::tags::Tag = 19;
pub const TAG_PRE: crate::tags::Tag = 20;
pub const TAG_BLOCKQUOTE: crate::tags::Tag = 21;
pub const TAG_H1: crate::tags::Tag = 22;
pub const TAG_H2: crate::tags::Tag = 23;
pub const TAG_H3: crate::tags::Tag = 24;
pub const TAG_H4: crate::tags::Tag = 25;
pub const TAG_H5: crate::tags::Tag = 26;
pub const TAG_H6: crate::tags::Tag = 27;
pub const TAG_UL: crate::tags::Tag = 28;
pub const TAG_OL: crate::tags::Tag = 29;
pub const TAG_LI: crate::tags::Tag = 30;
pub const TAG_DL: crate::tags::Tag = 31;
pub const TAG_DT: crate::tags::Tag = 32;
pub const TAG_DD: crate::tags::Tag = 33;
pub const TAG_TABLE: crate::tags::Tag = 34;
pub const TAG_THEAD: crate::tags::Tag = 35;
pub const TAG_TBODY: crate::tags::Tag = 36;
pub const TAG_TFOOT: crate::tags::Tag = 37;
pub const TAG_TR: crate::tags::Tag = 38;
pub const TAG_TD: crate::tags::Tag = 39;
pub const TAG_TH: crate::tags::Tag = 40;
pub const TAG_CAPTION: crate::tags::Tag = 41;
pub const TAG_IMG: crate::tags::Tag = 42;
pub const TAG_BR: crate::tags::Tag = 43;
pub const TAG_HR: crate::tags::Tag = 44;
pub const TAG_FORM: crate::tags::Tag = 45;
pub const TAG_INPUT: crate::tags::Tag = 46;
pub const TAG_BUTTON: crate::tags::Tag = 47;
pub const TAG_SELECT: crate::tags::Tag = 48;
pub const TAG_OPTION: crate::tags::Tag = 49;
pub const TAG_LABEL: crate::tags::Tag = 50;
pub const TAG_TEXTAREA: crate::tags::Tag = 51;
pub const TAG_HEADER: crate::tags::Tag = 52;
pub const TAG_FOOTER: crate::tags::Tag = 53;
pub const TAG_NAV: crate::tags::Tag = 54;
pub const TAG_MAIN: crate::tags::Tag = 55;
pub const TAG_SECTION: crate::tags::Tag = 56;
pub const TAG_ARTICLE: crate::tags::Tag = 57;
pub const TAG_ASIDE: crate::tags::Tag = 58;
pub const TAG_FIGURE: crate::tags::Tag = 59;
pub const TAG_FIGCAPTION: crate::tags::Tag = 60;
pub const TAG_ADDRESS: crate::tags::Tag = 61;
pub const TAG_SMALL: crate::tags::Tag = 62;
pub const TAG_BIG: crate::tags::Tag = 63;
pub const TAG_SUB: crate::tags::Tag = 64;
pub const TAG_SUP: crate::tags::Tag = 65;
pub const TAG_MARK: crate::tags::Tag = 66;
pub const TAG_TIME: crate::tags::Tag = 67;
pub const TAG_Q: crate::tags::Tag = 68;
pub const TAG_CITE: crate::tags::Tag = 69;
pub const TAG_ABBR: crate::tags::Tag = 70;
pub const TAG_DFN: crate::tags::Tag = 71;
pub const TAG_KBD: crate::tags::Tag = 72;
pub const TAG_SAMP: crate::tags::Tag = 73;
pub const TAG_VAR: crate::tags::Tag = 74;
pub const TAG_FONT: crate::tags::Tag = 75;
pub const TAG_CENTER: crate::tags::Tag = 76;
pub const TAG_STRIKE: crate::tags::Tag = 77;
pub const TAG_TT: crate::tags::Tag = 78;
pub const TAG_WBR: crate::tags::Tag = 79;
pub const TAG_NOSCRIPT: crate::tags::Tag = 80;
pub const TAG_IFRAME: crate::tags::Tag = 81;
pub const TAG_OBJECT: crate::tags::Tag = 82;
pub const TAG_PARAM: crate::tags::Tag = 83;
pub const TAG_SOURCE: crate::tags::Tag = 84;
pub const TAG_TRACK: crate::tags::Tag = 85;
pub const TAG_VIDEO: crate::tags::Tag = 86;
pub const TAG_AUDIO: crate::tags::Tag = 87;
pub const TAG_CANVAS: crate::tags::Tag = 88;
pub const TAG_SVG: crate::tags::Tag = 89;
pub const TAG_MATH: crate::tags::Tag = 90;
pub const TAG_MI: crate::tags::Tag = 91;
pub const TAG_MO: crate::tags::Tag = 92;
pub const TAG_MN: crate::tags::Tag = 93;
pub const TAG_MS: crate::tags::Tag = 94;
pub const TAG_MTEXT: crate::tags::Tag = 95;
pub const TAG_ANNOTATION_XML: crate::tags::Tag = 96;
pub const TAG_FOREIGNOBJECT: crate::tags::Tag = 97;
pub const TAG_DESC: crate::tags::Tag = 98;
pub const TAG_MGLYPH: crate::tags::Tag = 99;
pub const TAG_MALIGNMARK: crate::tags::Tag = 100;
pub const TAG_LISTING: crate::tags::Tag = 101;
pub const TAG_PLAINTEXT: crate::tags::Tag = 102;
pub const TAG_XMP: crate::tags::Tag = 103;
pub const TAG_NOEMBED: crate::tags::Tag = 104;
pub const TAG_NOFRAMES: crate::tags::Tag = 105;
pub const TAG_RUBY: crate::tags::Tag = 106;
pub const TAG_RP: crate::tags::Tag = 107;
pub const TAG_RT: crate::tags::Tag = 108;
pub const TAG_RTC: crate::tags::Tag = 109;
pub const TAG_RB: crate::tags::Tag = 110;
pub const TAG_FRAMESET: crate::tags::Tag = 111;
pub const TAG_FRAME: crate::tags::Tag = 112;
pub const TAG_OPTGROUP: crate::tags::Tag = 113;
pub const TAG_LEGEND: crate::tags::Tag = 114;
pub const TAG_FIELDSET: crate::tags::Tag = 115;
pub const TAG_BASE: crate::tags::Tag = 116;
pub const TAG_COL: crate::tags::Tag = 117;
pub const TAG_COLGROUP: crate::tags::Tag = 118;
pub const TAG_AREA: crate::tags::Tag = 119;
pub const TAG_MAP: crate::tags::Tag = 120;
pub const TAG_EMBED: crate::tags::Tag = 121;
pub const TAG_DIR: crate::tags::Tag = 122;
pub const TAG_MENU: crate::tags::Tag = 123;
pub const TAG_APPLET: crate::tags::Tag = 124;
pub const TAG_MARQUEE: crate::tags::Tag = 125;
pub const TAG_BASEFONT: crate::tags::Tag = 126;
pub const TAG_KEYGEN: crate::tags::Tag = 127;
pub const TAG_TEMPLATE: crate::tags::Tag = 128;
pub const TAG_NOBR: crate::tags::Tag = 129;
pub const TAG_DETAILS: crate::tags::Tag = 130;
pub const TAG_DIALOG: crate::tags::Tag = 131;
pub const TAG_HGROUP: crate::tags::Tag = 132;
pub const TAG_SEARCH: crate::tags::Tag = 133;
pub const TAG_SUMMARY: crate::tags::Tag = 134;
pub const TAG_BGSOUND: crate::tags::Tag = 135;
pub const TAG_IMAGE: crate::tags::Tag = 136;
