/* lodash 4.17.21 互換スモークテスト（AKL で lodash.js 本体をロードした後に実行する）。
 * 使い方: cat /path/to/lodash.js tests/lodash_smoke.js > combined.js && akl combined.js
 * `_`（lodash）がグローバルに存在する前提。すべて V8/node で検証済みの期待値。 */
var __out = [];
function T(name, got, want) {
  var ok = String(got) === String(want);
  __out.push((ok ? "OK " : "NG ") + name + " = " + String(got) + (ok ? "" : " (want " + String(want) + ")"));
}

T("_.VERSION", _.VERSION, "4.17.21");
T("_.map", JSON.stringify(_.map([1,2,3], function(x){ return x * 2; })), "[2,4,6]");
T("_.filter", JSON.stringify(_.filter([1,2,3,4], function(x){ return x % 2 == 0; })), "[2,4]");
T("_.reduce", _.reduce([1,2,3,4], function(a,b){ return a + b; }, 0), "10");
T("_.reduceRight", _.reduceRight([[0,1],[2,3],[4,5]], function(a,b){ return a.concat(b); }, []), "4,5,2,3,0,1");
T("_.forEach sum", (function(){ var s = 0; _.forEach([1,2,3], function(v){ s += v; }); return s; })(), "6");
T("_.forEachRight", (function(){ var s = ""; _.forEachRight([1,2,3], function(v){ s += v; }); return s; })(), "321");
T("_.mapValues", JSON.stringify(_.mapValues({a:1,b:2}, function(v){ return v*2; })), '{"a":2,"b":4}');
T("_.mapKeys", JSON.stringify(_.mapKeys({a:1,b:2}, function(v,k){ return k + v; })), '{"a1":1,"b2":2}');
T("_.groupBy", JSON.stringify(_.groupBy([1.2,1.8,2.3], function(x){ return Math.floor(x); })), '{"1":[1.2,1.8],"2":[2.3]}');
T("_.countBy", (function(){ var r = _.countBy([6.1,4.2,6.3], function(x){ return Math.floor(x); }); return r[4] + "|" + r[6]; })(), "1|2");
T("_.keyBy", JSON.stringify(_.keyBy([{id:"a"},{id:"b"}], "id")), '{"a":{"id":"a"},"b":{"id":"b"}}');
T("_.partition", JSON.stringify(_.partition([1,2,3,4], function(x){ return x % 2 == 0; })), "[[2,4],[1,3]]");
T("_.find", JSON.stringify(_.find([{a:1},{a:2}], function(o){ return o.a == 2; })), '{"a":2}');
T("_.findLast", JSON.stringify(_.findLast([{a:1},{a:2}], function(o){ return o.a; })), '{"a":2}');
T("_.findIndex", _.findIndex([4,5,6], function(x){ return x > 4; }), "1");
T("_.findLastIndex", _.findLastIndex([4,5,6], function(x){ return x > 4; }), "2");
T("_.findKey", _.findKey({a:1,b:2}, function(v){ return v == 2; }), "b");
T("_.findLastKey", _.findLastKey({a:1,b:2}, function(v){ return v >= 1; }), "b");
T("_.reject", JSON.stringify(_.reject([1,2,3,4], function(x){ return x % 2 == 0; })), "[1,3]");
T("_.flatMap", JSON.stringify(_.flatMap([1,2], function(x){ return [x, x]; })), "[1,1,2,2]");
T("_.flatMapDeep", JSON.stringify(_.flatMapDeep([1,2], function(x){ return [[x]]; })), "[1,2]");
T("_.every", _.every([true, 1, null, "yes"], Boolean), "false");
T("_.some", _.some([null, 0, "yes"], Boolean), "true");
T("_.invokeMap", JSON.stringify(_.invokeMap([[5,1,7],[3,2,1]], "sort")), "[[1,5,7],[1,2,3]]");
T("_.sumBy", _.sumBy([{n:1},{n:2}], "n"), "3");
T("_.meanBy", _.meanBy([{n:2},{n:4}], "n"), "3");
T("_.maxBy", JSON.stringify(_.maxBy([{n:1},{n:3}], "n")), '{"n":3}');
T("_.minBy", JSON.stringify(_.minBy([{n:1},{n:3}], "n")), '{"n":1}');
T("_.sortBy", JSON.stringify(_.sortBy([3,1,2])), "[1,2,3]");
T("_.orderBy", JSON.stringify(_.orderBy([{a:2},{a:1}], ["a"], ["asc"])), '[{"a":1},{"a":2}]');
T("_.get", _.get({a:{b:42}}, "a.b"), "42");
T("_.get default", _.get({}, "x.y", "dflt"), "dflt");
T("_.get neg idx", _.get({a:[10,20]}, "a[-1]"), "undefined"); /* V8 も undefined */
T("_.has", _.has({a:{b:1}}, "a.b"), "true");
T("_.hasIn", _.hasIn({a:{b:1}}, "a.b"), "true");
T("_.set", JSON.stringify(_.set({}, "a.b.c", 3)), '{"a":{"b":{"c":3}}}');
T("_.unset", (function(){ var o = {a:{b:1}}; _.unset(o, "a.b"); return JSON.stringify(o); })(), '{"a":{}}');
T("_.update", JSON.stringify(_.update({a:{b:1}}, "a.b", function(x){ return x + 1; })), '{"a":{"b":2}}');
T("_.result", _.result({a:{b:3}}, "a.b"), "3");
T("_.result fn", _.result({a:function(){ return 4; }}, "a"), "4");
T("_.at", JSON.stringify(_.at({a:[{b:1},{c:2}]}, ["a[0].b","a[1].c"])), "[1,2]");
T("_.pick", JSON.stringify(_.pick({a:1,b:2,c:3}, ["a","c"])), '{"a":1,"c":3}');
T("_.omit", JSON.stringify(_.omit({a:1,b:2,c:3}, ["b"])), '{"a":1,"c":3}');
T("_.pickBy", JSON.stringify(_.pickBy({a:1,b:2}, function(v){ return v > 1; })), '{"b":2}');
T("_.omitBy", JSON.stringify(_.omitBy({a:1,b:2}, function(v){ return v > 1; })), '{"a":1}');
T("_.assign", JSON.stringify(_.assign({a:1},{b:2})), '{"a":1,"b":2}');
T("_.merge", JSON.stringify(_.merge({a:{x:1}}, {a:{y:2}})), '{"a":{"x":1,"y":2}}');
T("_.defaults", JSON.stringify(_.defaults({a:1},{a:9,b:2})), '{"a":1,"b":2}');
T("_.defaultsDeep", JSON.stringify(_.defaultsDeep({a:{x:1}}, {a:{y:2}})), '{"a":{"x":1,"y":2}}');
T("_.extend", JSON.stringify(_.extend({a:1},{b:2})), '{"a":1,"b":2}');
T("_.assignIn", JSON.stringify(_.assignIn({a:1},{b:2})), '{"a":1,"b":2}');
T("_.create", (function(){ var p = {x:1}; var o = _.create(p); return o.x; })(), "1");
T("_.clone", JSON.stringify(_.clone({a:1,b:[2]})), '{"a":1,"b":[2]}');
T("_.cloneDeep", JSON.stringify(_.cloneDeep({a:{b:{c:1}}})), '{"a":{"b":{"c":1}}}');
T("_.cloneDeep arr", JSON.stringify(_.cloneDeep([{a:[1]}])), '[{"a":[1]}]');
T("_.cloneDeep date", (function(){ var d = new Date(123); var c = _.cloneDeep(d); return c.getTime(); })(), "123");
T("_.cloneDeep regexp", (function(){ var r = /ab+/gi; var c = _.cloneDeep(r); return c.source + c.flags; })(), "ab+gi");
T("_.isEqual", _.isEqual({a:[1,2]}, {a:[1,2]}), "true");
T("_.isEqual NaN", _.isEqual(NaN, NaN), "true");
T("_.isEqual date", _.isEqual(new Date(1), new Date(1)), "true");
T("_.isEqual regexp", _.isEqual(/a/g, /a/g), "true");
T("_.isEqual diff", _.isEqual({a:1}, {a:2}), "false");
T("_.isMatch", _.isMatch({a:1,b:2}, {b:2}), "true");
T("_.isMatch deep", _.isMatch({a:{b:1}}, {a:{b:1}}), "true");
T("_.matches", _.matches({a:1})({a:1,b:2}), "true");
T("_.matchesProperty", _.matchesProperty("a.b", 1)({a:{b:1}}), "true");
T("_.conformsTo", _.conformsTo({a:5}, {a:function(x){ return x > 3; }}), "true");
T("_.keys", JSON.stringify(_.keys({x:1,y:2})), '["x","y"]');
T("_.values", JSON.stringify(_.values({x:1,y:2})), "[1,2]");
T("_.toPairs", JSON.stringify(_.toPairs({a:1,b:2})), '[["a",1],["b",2]]');
T("_.fromPairs", JSON.stringify(_.fromPairs([["a",1],["b",2]])), '{"a":1,"b":2}');
T("_.zip", JSON.stringify(_.zip(["a","b"],[1,2])), '[["a",1],["b",2]]');
T("_.unzip", JSON.stringify(_.unzip([["a",1],["b",2]])), '[["a","b"],[1,2]]');
T("_.zipObject", JSON.stringify(_.zipObject(["a","b"],[1,2])), '{"a":1,"b":2}');
T("_.zipObjectDeep", JSON.stringify(_.zipObjectDeep(["a.b"],[1])), '{"a":{"b":1}}');
T("_.zipWith", JSON.stringify(_.zipWith([1,2],[10,20], function(a,b){ return a + b; })), "[11,22]");
T("_.unzipWith", JSON.stringify(_.unzipWith([[1,10,100],[2,20,200]], function(a,b,c){ return a + b + c; })), "[null,null,null]"); /* V8 も [null,null,null]（unzip 後は 2 要素グループ） */
T("_.flatten", JSON.stringify(_.flatten([1,[2,[3]]])), "[1,2,[3]]");
T("_.flattenDeep", JSON.stringify(_.flattenDeep([1,[2,[3,[4]]]])), "[1,2,3,4]");
T("_.uniq", JSON.stringify(_.uniq([1,2,1,3,2])), "[1,2,3]");
T("_.uniqBy", JSON.stringify(_.uniqBy([2.1,1.2,2.3], Math.floor)), "[2.1,1.2]");
T("_.union", JSON.stringify(_.union([1,2],[2,3])), "[1,2,3]");
T("_.unionBy", JSON.stringify(_.unionBy([2.1],[1.2,2.3], Math.floor)), "[2.1,1.2]");
T("_.intersection", JSON.stringify(_.intersection([2,1],[2,3])), "[2]");
T("_.difference", JSON.stringify(_.difference([2,1],[2,3])), "[1]");
T("_.xor", JSON.stringify(_.xor([2,1],[2,3])), "[1,3]");
T("_.xorBy", JSON.stringify(_.xorBy([2.1,1.2],[2.3,3.4], Math.floor)), "[1.2,3.4]");
T("_.without", JSON.stringify(_.without([2,1,2,3], 1, 2)), "[3]");
T("_.chunk", JSON.stringify(_.chunk([1,2,3,4,5], 2)), "[[1,2],[3,4],[5]]");
T("_.compact", JSON.stringify(_.compact([0,1,false,2,"",3])), "[1,2,3]");
T("_.concat", JSON.stringify(_.concat([1], 2, [3])), "[1,2,3]");
T("_.drop", JSON.stringify(_.drop([1,2,3], 2)), "[3]");
T("_.take", JSON.stringify(_.take([1,2,3], 2)), "[1,2]");
T("_.dropWhile", JSON.stringify(_.dropWhile([1,2,3,4], function(x){ return x < 3; })), "[3,4]");
T("_.takeWhile", JSON.stringify(_.takeWhile([1,2,3,4], function(x){ return x < 3; })), "[1,2]");
T("_.fill", JSON.stringify(_.fill([1,2,3], "a")), '["a","a","a"]');
T("_.remove", (function(){ var a = [1,2,3,4]; _.remove(a, function(x){ return x % 2 == 0; }); return JSON.stringify(a); })(), "[1,3]");
T("_.pull", JSON.stringify(_.pull([1,2,3,1,2], 1, 2)), "[3]");
T("_.pullAll", JSON.stringify(_.pullAll([1,2,3,1,2], [1,2])), "[3]");
T("_.pullAt", JSON.stringify(_.pullAt([5,10,15,20], [1,3])), "[10,20]");
T("_.sortedIndex", _.sortedIndex([30,50], 40), "1");
T("_.sortedIndexBy", _.sortedIndexBy([{x:30},{x:50}], {x:40}, "x"), "1");
T("_.sortedIndexOf", _.sortedIndexOf([4,5,5,5,6], 5), "1");
T("_.sortedLastIndex", _.sortedLastIndex([4,5,5,5,6], 5), "4");
T("_.sortedLastIndexOf", _.sortedLastIndexOf([4,5,5,5,6], 5), "3");
T("_.sortedUniq", JSON.stringify(_.sortedUniq([1,1,2,3,3])), "[1,2,3]");
T("_.sortedUniqBy", JSON.stringify(_.sortedUniqBy([1.1,1.2,2.3,2.4], Math.floor)), "[1.1,2.3]");
T("_.includes", _.includes([1,2,3], 2), "true");
T("_.indexOf", _.indexOf([1,2,3], 3), "2");
T("_.lastIndexOf", _.lastIndexOf([1,2,1,2], 2), "3");
T("_.nth", _.nth(["a","b","c"], 1), "b");
T("_.nth neg", _.nth(["a","b","c"], -1), "c");
T("_.first", _.first([5,6,7]), "5");
T("_.head", _.head([1,2,3]), "1");
T("_.last", _.last([1,2,3]), "3");
T("_.initial", JSON.stringify(_.initial([1,2,3])), "[1,2]");
T("_.tail", JSON.stringify(_.tail([1,2,3])), "[2,3]");
T("_.join", _.join([1,2,3], "-"), "1-2-3");
T("_.reverse", JSON.stringify(_.reverse([1,2,3])), "[3,2,1]");
T("_.slice", JSON.stringify(_.slice([1,2,3,4], 1, 3)), "[2,3]");
T("_.castArray", JSON.stringify(_.castArray(1)), "[1]");
T("_.range", JSON.stringify(_.range(4)), "[0,1,2,3]");
T("_.rangeStep", JSON.stringify(_.range(1, 7, 2)), "[1,3,5]");
T("_.times", JSON.stringify(_.times(3, function(i){ return i * 2; })), "[0,2,4]");
T("_.identity", _.identity(42), "42");
T("_.constant", _.constant(9)(), "9");
T("_.noop", _.noop(), "undefined");
T("_.property", _.property("a.b")({a:{b:5}}), "5");
T("_.propertyOf", _.propertyOf({a:{b:2}})("a.b"), "2");
T("_.iteratee", _.iteratee("a.b")({a:{b:7}}), "7");
T("_.iteratee fn", _.iteratee(function(x){ return x; })(1), "1");
T("_.iteratee arr", _.iteratee(["a", 1])({a:1}), "true");
T("_.iteratee obj", _.iteratee({a:1})({a:1,b:2}), "true");
T("_.eq", _.eq(1, 1), "true");
T("_.gt", _.gt(3, 1), "true");
T("_.gte", _.gte(3, 3), "true");
T("_.lt", _.lt(1, 3), "true");
T("_.lte", _.lte(3, 3), "true");
T("_.add", _.add(2, 3), "5");
T("_.subtract", _.subtract(5, 2), "3");
T("_.multiply", _.multiply(3, 4), "12");
T("_.divide", _.divide(6, 2), "3");
T("_.max", _.max([3,1,7]), "7");
T("_.min", _.min([3,1,7]), "1");
T("_.sum", _.sum([1,2,3]), "6");
T("_.mean", _.mean([1,2,3,4]), "2.5");
T("_.round", _.round(4.006, 2), "4.01");
T("_.ceil", _.ceil(4.006, 2), "4.01");
T("_.floor", _.floor(4.956, 2), "4.95");
T("_.clamp", _.clamp(10, 0, 5), "5");
T("_.inRange", _.inRange(3, 2, 5), "true");
T("_.random int", _.isNumber(_.random(1, 10)), "true");
T("_.random range", (function(){ var ok = true; for (var i = 0; i < 20; i++) { var v = _.random(1, 3); if (v < 1 || v > 3) ok = false; } return ok; })(), "true");
T("_.toNumber", _.toNumber("3.5"), "3.5");
T("_.toInteger", _.toInteger(3.7), "3");
T("_.toFinite", _.toFinite("4.2"), "4.2");
T("_.toString", _.toString([1,2,3]), "1,2,3");
T("_.toArray", JSON.stringify(_.toArray({a:1,b:2})), "[1,2]");
T("_.toArray str", JSON.stringify(_.toArray("abc")), '["a","b","c"]');
T("_.toArray map", (function(){ var m = new Map([["a",1],["b",2]]); return JSON.stringify(_.toArray(m)); })(), '[["a",1],["b",2]]');
T("_.toArray set", (function(){ var s = new Set([1,2,3]); return JSON.stringify(_.toArray(s)); })(), "[1,2,3]");
T("_.toPath", JSON.stringify(_.toPath("a[0].b.c")), '["a","0","b","c"]');
T("_.size", _.size({a:1,b:2}), "2");
T("_.size str", _.size("pebbles"), "7");
T("_.size map", _.size(new Map([[1,2]])), "1");
T("_.size set", _.size(new Set([1])), "1");
T("_.sample", (function(){ var v = _.sample([1,2,3]); return _.includes([1,2,3], v); })(), "true");
T("_.sampleSize", _.sampleSize([1,2,3,4], 2).length, "2");
T("_.shuffle len", _.shuffle([1,2,3,4]).length, "4");
T("_.isEmpty", _.isEmpty({}), "true");
T("_.isEmpty arr", _.isEmpty([1]), "false");
T("_.isEmpty str", _.isEmpty(""), "true");
T("_.isEmpty map", _.isEmpty(new Map()), "true");
T("_.isArray", _.isArray([]), "true");
T("_.isObject", _.isObject({}), "true");
T("_.isObject fn", _.isObject(_.noop), "true");
T("_.isFunction", _.isFunction(_.map), "true");
T("_.isString", _.isString("s"), "true");
T("_.isNumber", _.isNumber(3), "true");
T("_.isNaN", _.isNaN(NaN), "true");
T("_.isNil", _.isNil(null), "true");
T("_.isUndefined", _.isUndefined(undefined), "true");
T("_.isNull", _.isNull(null), "true");
T("_.isBoolean", _.isBoolean(false), "true");
T("_.isDate", _.isDate(new Date()), "true");
T("_.isRegExp", _.isRegExp(/a/), "true");
T("_.isSymbol", _.isSymbol(Symbol("x")), "true");
T("_.isFinite", _.isFinite(3), "true");
T("_.isInteger", _.isInteger(3), "true");
T("_.isSafeInteger", _.isSafeInteger(3), "true");
T("_.isLength", _.isLength(3), "true");
T("_.isArrayLike", _.isArrayLike("abc"), "true");
T("_.isArrayLikeObject", _.isArrayLikeObject("abc"), "false");
T("_.isPlainObject", _.isPlainObject({}), "true");
T("_.isElement", _.isElement(null), "false");
T("_.isError", _.isError(new Error()), "true");
T("_.isMap", _.isMap(new Map()), "true");
T("_.isSet", _.isSet(new Set()), "true");
T("_.isWeakMap", _.isWeakMap(new WeakMap()), "true");
T("_.isWeakSet", _.isWeakSet(new WeakSet()), "true");
T("_.isTypedArray", _.isTypedArray(new Uint8Array(2)), "true");
T("_.isArrayBuffer", _.isArrayBuffer(new ArrayBuffer(2)), "true");
T("_.isDataView 無し", typeof _.isDataView, "undefined"); /* lodash 4.17.21 に存在しない */
T("_.isObjectLike", _.isObjectLike({}), "true");
T("_.isObjectLike prim", _.isObjectLike(null), "false");
T("_.isArguments", (function(){ return _.isArguments(arguments); })(), "false"); /* AKL の arguments は ARR 近似（callee なし。AKL_COMPAT） */
T("_.isEqualWith", (function(){ return _.isEqualWith({a:1}, {a:1}, function(a, b){ return a === b; }); })(), "false"); /* V8 も false（customizer が false を返すと深い比較しない） */
T("_.isMatchWith", (function(){ return _.isMatchWith({a:1}, {a:1}, function(a, b){ return a === b; }); })(), "true");
T("_.cloneWith", (function(){ var c = _.cloneWith({a:1}, function(v){ return v; }); return c.a; })(), "1");
T("_.cloneDeepWith", (function(){ var c = _.cloneDeepWith({a:1}, function(v){ return v; }); return c.a; })(), "1");
T("_.capitalize", _.capitalize("fred"), "Fred");
T("_.camelCase", _.camelCase("Foo Bar"), "fooBar");
T("_.kebabCase", _.kebabCase("fooBar baz"), "foo-bar-baz");
T("_.snakeCase", _.snakeCase("fooBar baz"), "foo_bar_baz");
T("_.startCase", _.startCase("fooBar"), "Foo Bar");
T("_.deburr", _.deburr("déjà vu"), "deja vu");
T("_.words", JSON.stringify(_.words("fred, barney, & pebbles")), '["fred","barney","pebbles"]');
T("_.toUpper", _.toUpper("abc"), "ABC");
T("_.toLower", _.toLower("ABC"), "abc");
T("_.upperFirst", _.upperFirst("fred"), "Fred");
T("_.lowerFirst", _.lowerFirst("Fred"), "fred");
T("_.repeat", _.repeat("ab", 3), "ababab");
T("_.pad", _.pad("abc", 7, "_-"), "_-abc_-");
T("_.padStart", _.padStart("abc", 6, "_-"), "_-_abc");
T("_.padEnd", _.padEnd("abc", 6, "_-"), "abc_-_");
T("_.trim", _.trim("  abc  "), "abc");
T("_.trimStart", _.trimStart("  abc  "), "abc  ");
T("_.trimEnd", _.trimEnd("  abc  "), "  abc");
T("_.trim chars", _.trim("-_-abc-_-", "_-"), "abc");
T("_.truncate", _.truncate("hi-diddly-ho there, neighborino", {length: 24, separator: " "}), "hi-diddly-ho there,...");
T("_.escape", _.escape("fred, barney, & pebbles"), "fred, barney, &amp; pebbles");
T("_.escape all", _.escape("&<>\"'"), "&amp;&lt;&gt;&quot;&#39;");
T("_.unescape", _.unescape("fred, barney, &amp; pebbles"), "fred, barney, & pebbles");
T("_.unescape all", _.unescape("&amp;&lt;&gt;&quot;&#39;"), "&<>\"'");
T("_.escapeRegExp", _.escapeRegExp("[lodash](https://lodash.com/)"), "\\[lodash\\]\\(https://lodash\\.com/\\)");
T("_.startsWith", _.startsWith("abc", "a"), "true");
T("_.endsWith", _.endsWith("abc", "c"), "true");
T("_.includes str", _.includes("abc", "b"), "true");
T("_.split", JSON.stringify(_.split("a-b-c", "-")), '["a","b","c"]');
T("_.split limit", JSON.stringify(_.split("a-b-c", "-", 2)), '["a","b"]');
T("_.replace", _.replace("Hi Fred", "Fred", "Barney"), "Hi Barney");
T("_.parseInt", _.parseInt("08"), "8");
T("_.parseInt base", _.parseInt("0x10", 16), "16");
T("_.curry", _.curry(function(a,b,c){ return a+b+c; })(1)(2)(3), "6");
T("_.curryRight", _.curryRight(function(a,b){ return a+b; })(1)(2), "3");
T("_.partial", _.partial(function(a,b,c){ return a+b+c; }, 1, 2)(3), "6");
T("_.partialRight", _.partialRight(function(a,b,c){ return a + b + c; }, 2, 3)(1), "6");
T("_.partial placeholder", (function(){ var f = _.partial(function(a,b,c){ return a + b + c; }, _, 2); return f(1, 3); })(), "6");
T("_.curry placeholder", (function(){ var f = _.curry(function(a,b,c){ return a + b + c; }); return f(1, _, 3)(2); })(), "6");
T("_.memoize", _.memoize(function(x){ return x * 10; })(5), "50");
T("_.memoize cache", (function(){ var calls = 0; var f = _.memoize(function(x){ calls++; return x; }); f(1); f(1); return calls; })(), "1");
T("_.once", (function(){ var f = _.once(function(){ return 7; }); f(); return f(); })(), "7");
T("_.before", (function(){ var f = _.before(3, function(){ return "hi"; }); return f() + f() + f(); })(), "hihihi");
T("_.after", (function(){ var c = 0; var f = _.after(2, function(){ return "done"; }); f(); f(); return f(); })(), "done");
T("_.bind", _.bind(function(a,b){ return this.x + a + b; }, {x:10})(1,2), "13");
T("_.bindKey", (function(){ var o = {x:10, f:function(a){ return this.x + a; }}; return _.bindKey(o, "f")(5); })(), "15");
T("_.wrap", _.wrap(_.escape, function(f, s){ return "<b>" + f(s) + "</b>"; })("a<b>"), "<b>a&lt;b&gt;</b>");
T("_.negate", _.negate(function(){ return true; })(), "false");
T("_.ary", _.ary(function(a,b,c){ return [a,b,c]; }, 2)(1,2,3), "1,2,"); /* String([1,2,undefined]) = "1,2,"（V8 一致） */
T("_.unary", _.unary(function(a,b){ return [a,b]; })(1,2), "1,"); /* String([1,undefined]) = "1,"（V8 一致） */
T("_.spread", _.spread(function(a,b){ return a + b; })([1,2]), "3");
T("_.flip", JSON.stringify(_.flip(function(a,b){ return [a,b]; })(1,2)), "[2,1]");
T("_.rearg", JSON.stringify(_.rearg(function(a,b,c){ return [a,b,c]; }, [2,0,1])(1,2,3)), "[3,1,2]");
T("_.rest", _.rest(function(a,b,c){ return [a,b,c]; })(1,2,3), "1,2,3"); /* [1,[2,3]] の String（V8 一致） */
T("_.over", _.over([function(x){return x+1;}, function(x){return x*2;}])(3), "4,6");
T("_.overEvery", _.overEvery([function(x){return x>1;}, function(x){return x<3;}])(2), "true");
T("_.overSome", _.overSome([function(x){return x>9;}, function(x){return x>1;}])(2), "true");
T("_.flow", _.flow([function(x){return x+1;}, function(x){return x*2;}])(1), "4");
T("_.flowRight", _.flowRight([function(x){return x+1;}, function(x){return x*2;}])(1), "3");
T("_.method", _.method("a.b")({a:{b:function(){ return 9; }}}), "9");
T("_.methodOf", _.methodOf({a:{b:function(){ return 5; }}})("a.b"), "5");
T("_.mixin", (function(){ var o = {}; _.mixin(o); return typeof o.each; })(), "undefined"); /* V8 も undefined（source なし mixin） */
T("_.mixin fn", (function(){ var o = {}; _.mixin(o, {f:function(){ return 3; }}); return o.f(); })(), "3");
T("_.cond", _.cond([[function(o){return o.a;}, function(){ return "has a"; }]])({a:1}), "has a");
T("_.conforms", _.conforms({a:function(x){ return x > 1; }})({a:2}), "true");
T("_.attempt", _.attempt(function(){ return 3; }), "3");
T("_.attempt err", (function(){ var r = _.attempt(function(){ throw new TypeError("boom"); }); return r instanceof TypeError; })(), "true");
T("_.attempt err2", (function(){ var r = _.attempt(function(){ throw new Error("boom"); }); return r.message; })(), "boom");
T("_.delay type", typeof _.delay, "function");
T("_.defer type", typeof _.defer, "function");
T("_.delay returns", (function(){ var r = _.delay(function(){}, 0); return typeof r == "number"; })(), "true");
T("_.now type", typeof _.now(), "number");
T("_.uniqueId", (function(){ var a = _.uniqueId("x_"); var b = _.uniqueId("x_"); return a != b; })(), "true");
T("_.throttle basic", (function(){ var c = 0; var f = _.throttle(function(){ c++; return c; }, 50); f(); f(); return c >= 1; })(), "true");
T("_.debounce basic", (function(){ var c = 0; var f = _.debounce(function(){ c++; }, 50); f(); f(); return true; })(), "true");
T("_.debounce type", typeof _.debounce, "function");
T("_.chain", _.chain([1,2,3]).map(function(x){return x*2;}).sum().value(), "12");
T("_.chain value", _.chain(5).add(3).value(), "8");
T("_.chain push", (function(){ var w = _.chain([1,2]); w.push(3); return w.value(); })(), "1,2"); /* push は新ラッパーを返す（戻りを捨てると元のまま。V8 一致） */
T("_.chain first", _.chain([1,2,3]).first().value(), "1");
T("_.chain last", _.chain([1,2,3]).last().value(), "3");
T("_.chain flatten", _.chain([1,[2]]).flatten().value(), "1,2");
T("_.chain uniq", _.chain([1,1,2]).uniq().value(), "1,2");
T("_.chain sortBy", _.chain([3,1,2]).sortBy().value(), "1,2,3");
T("_.chain reduce", _.chain([1,2,3]).reduce(function(a,b){ return a + b; }).value(), "6");
T("_.chain filter", _.chain([1,2,3,4]).filter(function(x){ return x % 2 == 0; }).value(), "2,4");
T("_.chain map", _.chain([1,2]).map(function(x){ return x * 10; }).value(), "10,20");
T("_.chain concat", _.chain([1]).concat([2]).value(), "1,2");
T("_.chain reverse", _.chain([1,2,3]).reverse().value(), "3,2,1");
T("_.chain join", _.chain([1,2]).join("-").value(), "1-2");
T("_.chain get", _.chain({a:{b:2}}).get("a.b").value(), "2");
T("_.chain set", (function(){ var w = _.chain({}).set("a.b", 3); return JSON.stringify(w.value()); })(), '{"a":{"b":3}}');
T("_.chain has", _.chain({a:1}).has("a").value(), "true");
T("_.chain commit", (function(){ var w = _.chain([1,2,3]).push(4).commit(); return w.value(); })(), "1,2,3,4");
T("_.chain plant", (function(){ var w1 = _.chain([1,2]); var w2 = w1.plant([3,4]); w2.push(5); return w1.value() + "|" + w2.value(); })(), "1,2|3,4");
T("_.chain next", (function(){ var w = _.chain([1,2]); var n = w.next(); return n.value; })(), "1");
T("_.chain toJSON", _.chain({a:1}).toJSON().a, "1");
T("_.chain valueOf", _.chain([1,2]).valueOf(), "1,2");
T("_.chain toString", _.chain([1,2]).value().toString(), "1,2"); /* wrapper.toString は inspect 形式（V8 は LodashWrapper {...}）なので value 後に評価 */
T("_.prototype method", (function(){ return typeof _.prototype.map; })(), "function");
T("_.placeholder", _.curry.placeholder === _, "true"); /* V8 でも _.placeholder 自体は _ と等しくない */
T("_.curry placeholder prop", _.curry.placeholder === _, "true");
T("_.bind placeholder prop", _.bind.placeholder === _, "true");
T("_.runInContext type", typeof _.runInContext, "function");
T("_.runInContext 2", (function(){ var o = _.runInContext(); return typeof o.map; })(), "function");
T("_.noConflict type", typeof _.noConflict, "function");
T("_.noConflict 2", (function(){ var o = _.noConflict(); return typeof o; })(), "function");
T("_.toJSON type", typeof _.toJSON, "undefined"); /* V8 でも undefined（wrapper メソッドのみ） */
T("_.valueOf type", typeof _.valueOf, "function");

var __ng = 0, __ok = 0;
for (var i = 0; i < __out.length; i++) {
  if (__out[i].indexOf("OK") === 0) __ok++; else { __ng++; }
}
if (__ng > 0) {
  for (var i = 0; i < __out.length; i++) {
    if (__out[i].indexOf("OK") !== 0) throw new Error(__out[i]);
  }
}
"lodash-smoke ok=" + __ok + " ng=" + __ng
