#!/usr/bin/env python3
# Ifuto Browser — 文字コード変換表生成器（src/charset_tables_gen.h の正本）
#
# 設計（docs/CHARSET.md 凍結）:
#   - tbl_jis208[8836]: WHATWG shift_jis pointer / EUC ku-ten 共通の一次索引
#       idx = (ku-1)*94 + (ten-1) → Unicode BMP（無効は 0 → U+FFFD）
#     正本は python codec の euc_jp（JIS X 0208 面）。SJIS strict との全セル
#     一致を本生成器が交叉検証する（不一致なら生成失敗 = 表は両 codec の合意点のみ）。
#   - tbl_jis212[8836]: EUC-JP SS3（0x8F）の JIS X 0212 面。同上。
#   - tbl_sjis_ext[]: cp932 が復号できて strict shift_jis が不可/異義のバイト対
#     （NEC選定・IBM拡張・波ダッシュ 6 件）。key = lead<<8|trail 昇順、上位16bit=key、
#     下位16bit=codepoint。C 側は ext 優先で二分探索 → tbl_jis208 の順。
#
# 波ダッシュ問題（0x8160 等 6 件）: cp932 系（windows-31j、実在の日本語 Web の
# 実効エンコーディング）を採る確定方針。乖離は docs/CHARSET.md に明記。
#
# 使い方:
#   gen_charset.py            src/charset_tables_gen.h を生成
#   gen_charset.py --verify   再生成してコミット済みヘッダと一致照合（exit 1=差異）
import sys

OUT = "src/charset_tables_gen.h"
RUST_OUT = "rust/ifuto-core/src/charset_tables.rs"
JIS_CELLS = 94 * 94  # 8836


def jis208_table():
    """idx → BMP codepoint（無効 0）。正本=euc_jp codec。strict shift_jis と交叉検証。"""
    tbl = [0] * JIS_CELLS
    for ku in range(1, 95):
        for ten in range(1, 95):
            idx = (ku - 1) * 94 + (ten - 1)
            try:
                d = bytes([0xA0 + ku, 0xA0 + ten]).decode("euc_jp")
            except UnicodeDecodeError:
                continue
            assert len(d) == 1, (ku, ten, d)
            cp = ord(d)
            assert cp <= 0xFFFF, (ku, ten, hex(cp))
            # 交叉検証: 同一 idx に対応する strict shift_jis バイト対（存在すれば）
            # が同じ codepoint を指すこと。
            # idx → sjis pair: pointer = idx、WHATWG 公式の逆変換
            assert cp > 0
            tbl[idx] = cp
    return tbl


def jis212_table():
    tbl = [0] * JIS_CELLS
    for b1 in range(0xA1, 0xFF):
        for b2 in range(0xA1, 0xFF):
            try:
                d = bytes([0x8F, b1, b2]).decode("euc_jp")
            except UnicodeDecodeError:
                continue
            assert len(d) == 1 and ord(d) <= 0xFFFF
            tbl[(b1 - 0xA1) * 94 + (b2 - 0xA1)] = ord(d)
    return tbl


def sjis_ext_table(jis208):
    """cp932 専有/異義バイト対 → [(key, cp), ...] key=lead<<8|trail。波ダッシュ6件を留め置く。"""
    ext = []
    override = []
    for lead in list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD)):
        for trail in list(range(0x40, 0x7F)) + list(range(0x80, 0xFD)):
            b = bytes([lead, trail])
            try:
                d = b.decode("cp932")
            except UnicodeDecodeError:
                continue
            assert len(d) == 1 and ord(d) <= 0xFFFF, (b.hex(), d)
            try:
                d2 = b.decode("shift_jis")
            except UnicodeDecodeError:
                d2 = None
            if d2 == d:
                continue  # tbl_jis208 と合意 → ext 不要
            key = (lead << 8) | trail
            cp = ord(d)
            if d2 is not None:
                override.append((key, ord(d2), cp))
            ext.append((key, cp))
    # 交叉検証: tbl_jis208 経由の復号（pointer 公式）は strict shift_jis に一致するか
    for lead in list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD)):
        for trail in list(range(0x40, 0x7F)) + list(range(0x80, 0xFD)):
            b = bytes([lead, trail])
            try:
                d2 = b.decode("shift_jis")
            except UnicodeDecodeError:
                continue
            trail_off = 0x40 if trail < 0x7F else 0x41
            lead_off = 0x81 if lead < 0xA0 else 0xC1
            idx = (lead - lead_off) * 188 + (trail - trail_off)
            assert idx < JIS_CELLS, (b.hex(), idx)
            assert jis208[idx] == ord(d2), (b.hex(), d2, jis208[idx])
    # override は波ダッシュ系 6 件に留まることを機械固定（逸脱したら生成失敗）
    assert len(override) == 6, override
    exp = {0x8160: 0xFF5E, 0x8161: 0x2225, 0x817C: 0xFF0D,
           0x8191: 0xFFE0, 0x8192: 0xFFE1, 0x81CA: 0xFFE2}
    assert {k: cp for k, _, cp in override} == exp, override
    ext.sort()
    assert len({k for k, _ in ext}) == len(ext)  # key 一意性
    return ext


def emit(jis208, jis212, ext):
    lines = []
    A = lines.append
    A("/* generated by tools/gen_charset.py — 手編集禁止。再生成一致オラクル: --verify */")
    A("/* 正本: python codec（euc_jp / shift_jis / cp932）。設計凍結は docs/CHARSET.md */")
    A("#ifndef IF_CHARSET_TABLES_GEN_H")
    A("#define IF_CHARSET_TABLES_GEN_H")
    A("")
    A("#define IF_JIS_CELLS 8836u")
    A("")
    A("static const u16 if_jis208_tbl[IF_JIS_CELLS] = {")
    for i in range(0, JIS_CELLS, 16):
        A("    " + ",".join("0x%04x" % c if c else "0" for c in jis208[i:i + 16]) + ",")
    A("};")
    A("")
    A("static const u16 if_jis212_tbl[IF_JIS_CELLS] = {")
    for i in range(0, JIS_CELLS, 16):
        A("    " + ",".join("0x%04x" % c if c else "0" for c in jis212[i:i + 16]) + ",")
    A("};")
    A("")
    A("#define IF_SJIS_EXT_N %du" % len(ext))
    A("/* key<<16 | codepoint（key = lead<<8|trail、昇順。波ダッシュ 6 件は cp932 採用） */")
    A("static const u32 if_sjis_ext_tbl[IF_SJIS_EXT_N] = {")
    for i in range(0, len(ext), 8):
        A("    " + ",".join("0x%08xu" % ((k << 16) | c) for k, c in ext[i:i + 8]) + ",")
    A("};")
    A("")
    A("#endif")
    return "\n".join(lines) + "\n"


def emit_rust(jis208, jis212, ext):
    """同一表を Rust の const スライスとして出力（rust/ifuto-core/src/charset_tables.rs）。"""
    lines = []
    A = lines.append
    A("// generated by tools/gen_charset.py — 手編集禁止。再生成一致オラクル: --verify")
    A("// 正本: python codec（euc_jp / shift_jis / cp932）。設計凍結は docs/CHARSET.md")
    A("")
    A("/// JIS 面のセル数（94 区 × 94 点）。")
    A("pub const IF_JIS_CELLS: usize = 8836;")
    A("")
    A("/// JIS X 0208 面（SJIS pointer / EUC ku-ten 共通の一次索引）→ Unicode BMP（無効 0）。")
    A("#[rustfmt::skip]")
    A("pub const JIS208: &[u16] = &[")
    for i in range(0, JIS_CELLS, 16):
        A("    " + ",".join("0x%04x" % c if c else "0" for c in jis208[i:i + 16]) + ",")
    A("];")
    A("")
    A("/// JIS X 0212 面（EUC-JP SS3 0x8F）→ Unicode BMP（無効 0）。")
    A("#[rustfmt::skip]")
    A("pub const JIS212: &[u16] = &[")
    for i in range(0, JIS_CELLS, 16):
        A("    " + ",".join("0x%04x" % c if c else "0" for c in jis212[i:i + 16]) + ",")
    A("];")
    A("")
    A("/// cp932 専有/異義バイト対。各要素 = key<<16 | codepoint（key = lead<<8|trail、昇順）。")
    A("#[rustfmt::skip]")
    A("pub const SJIS_EXT: &[u32] = &[")
    for i in range(0, len(ext), 8):
        A("    " + ",".join("0x%08x" % ((k << 16) | c) for k, c in ext[i:i + 8]) + ",")
    A("];")
    return "\n".join(lines) + "\n"


def main():
    jis208 = jis208_table()
    jis212 = jis212_table()
    ext = sjis_ext_table(jis208)
    text = emit(jis208, jis212, ext)
    rust_text = emit_rust(jis208, jis212, ext)
    if "--verify" in sys.argv:
        try:
            cur = open(OUT, "r", encoding="utf-8").read()
        except OSError:
            print("MISSING", OUT)
            sys.exit(1)
        if cur != text:
            print("DIFF: charset_tables_gen.h != regeneration (run tools/gen_charset.py)")
            sys.exit(1)
        try:
            cur_rust = open(RUST_OUT, "r", encoding="utf-8").read()
        except OSError:
            print("MISSING", RUST_OUT)
            sys.exit(1)
        if cur_rust != rust_text:
            print("DIFF: charset_tables.rs != regeneration (run tools/gen_charset.py)")
            sys.exit(1)
        print("charset tables: verified == python codec regeneration (C + Rust)")
        sys.exit(0)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    with open(RUST_OUT, "w", encoding="utf-8") as f:
        f.write(rust_text)
    nonzero208 = sum(1 for c in jis208 if c)
    nonzero212 = sum(1 for c in jis212 if c)
    print("wrote %s + %s: jis208=%d cells, jis212=%d cells, sjis_ext=%d pairs"
          % (OUT, RUST_OUT, nonzero208, nonzero212, len(ext)))


if __name__ == "__main__":
    main()
