#!/usr/bin/env python3
"""src/dom.c の IF_TAGS テーブル（HTML タグ表）を Rust の const スライスへ変換する。

正本は src/dom.c（手管理。順序は dom.h の IfTag 列挙と 1:1。ズレは test_html の
round-trip テストが検出する）。本生成器は dom.c からテーブルを抽出して
rust/ifuto-core/src/tags_tables.rs を生成する。--verify は再抽出と照合。

name 長（C の n フィールド）は Rust では `str.len()` から導出するため、
「手書き長さミス」の検査（C の if_dom_tag_table_sane）が構造的に不要になる。
"""
import re
import sys

SRC = "src/dom.c"
RUST_OUT = "rust/ifuto-core/src/tags_tables.rs"

FLAGS = {"F_VOID": 1, "F_RAW": 2, "F_RCDATA": 4, "0": 0}


def extract():
    src = open(SRC, encoding="utf-8").read()
    m = re.search(
        r"static const struct \{[^}]*\} IF_TAGS\[IF_TAG_N_TAGS\] = \{(.*?)\n\};",
        src, re.S,
    )
    if not m:
        print("FAILED: IF_TAGS table not found in", SRC)
        sys.exit(1)
    body = m.group(1)
    raw = re.findall(r'\{\s*"([^"]*)",\s*(\d+),\s*([A-Za-z0-9_]+)\s*\}', body)
    rows = [(n, int(ln), FLAGS[f]) for (n, ln, f) in raw]
    # 不変条件: name 長 == 宣言 n
    for n, ln, _f in rows:
        if len(n) != ln:
            print("FAILED: length mismatch for", n, ln)
            sys.exit(1)
    return rows


def emit(rows):
    lines = []
    A = lines.append
    A("// generated by tools/gen_tags.py — 手編集禁止。再生成一致オラクル: --verify")
    A("// 正本: src/dom.c の IF_TAGS（dom.h の IfTag 列挙と 1:1）")
    A("#![allow(missing_docs)] // 生成定数は個別 doc を付けない（名前が自己説明的）")
    A("")
    A("/// flags ビット（C の F_VOID/F_RAW/F_RCDATA 相当）。")
    A("/// `F_VOID` = void 要素（閉じタグ不要）。")
    A("pub const F_VOID: u8 = 1;")
    A("/// `F_RAW` = rawtext 要素（文字参照を解釈しない）。")
    A("pub const F_RAW: u8 = 2;")
    A("/// `F_RCDATA` = rcdata 要素（`<title>` 等）。")
    A("pub const F_RCDATA: u8 = 4;")
    A("")
    A("/// (canonical lowercase name, flags) の表。index 0 = UNKNOWN（空名）。")
    A("/// name 長は `str.len()` から導出（C の手書き n フィールドは不要）。")
    A("pub const TAGS: &[(&str, u8)] = &[")
    for n, _ln, f in rows:
        A('    ("%s", %d),' % (n, f))
    A("];")
    A("")
    A("/// 各タグの ID 定数（match パターン用。name を大文字 + '-'→'_' に変換）。")
    for i, (n, _ln, _f) in enumerate(rows):
        ident = "UNKNOWN" if n == "" else n.upper().replace("-", "_")
        A("pub const TAG_%s: crate::tags::Tag = %d;" % (ident, i))
    return "\n".join(lines) + "\n"


def main():
    rows = extract()
    text = emit(rows)
    if "--verify" in sys.argv:
        try:
            cur = open(RUST_OUT, encoding="utf-8").read()
        except OSError:
            print("MISSING", RUST_OUT)
            sys.exit(1)
        if cur != text:
            print("DIFF: tags_tables.rs != regeneration (run tools/gen_tags.py)")
            sys.exit(1)
        print("tags tables: verified == src/dom.c IF_TAGS (%d tags)" % len(rows))
        sys.exit(0)
    with open(RUST_OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s: %d tags" % (RUST_OUT, len(rows)))


if __name__ == "__main__":
    main()
