#!/usr/bin/env python3
"""src/entities_gen.h を再生成する（決定的: CPython 標準ライブラリ html.entities 由来
— CPython が vendoring する WHATWG entities.json と同内容。2231 entries を期待）。

レイアウト（200KB binary 天井のための密エンコード、行は 8 バイト）:
  名前: NUL 無し連結 blob + u16 offset/u8 len（';' は含めない）
  flags: bit0=WITH_SEMI（';' つき正式形が存在）, bit1=LEGACY（裸キーあり）
  値: {u16 cp1, u16 cp2}。cp2==0 は単一コードポイント。
      単一 cp が >0xFFFF の場合だけ cp1=0xFFFF, cp2=IF_ENT_AUX32 の index とする
      （2-cp エントリに astral が来ないことは生成時に assert 済み）

検証すみ不変条件（assert で強制）:
  - エントリは 1 または 2 コードポイント
  - コードポイント 0 は存在しない（cp2==0 を「無し」とみなせる）
  - 2-cp エントリは両方 BMP（astral なし）→ astral は必ず単一 cp
  - 全エントリ名は ASCII alnum、長さ ≤ 255
"""
from html.entities import html5
import sys


def main(out_path):
    by_name = {}
    for key, value in html5.items():
        if key.endswith(';'):
            by_name.setdefault(key[:-1], {})['semi'] = value
        else:
            by_name.setdefault(key, {})['legacy'] = value

    names = sorted(by_name.keys(), key=lambda s: s.encode('ascii'))
    blob = bytearray()
    aux32 = []
    rows = []
    for nm in names:
        e = by_name[nm]
        value = e.get('semi', e.get('legacy'))
        cps = [ord(c) for c in value]
        assert len(cps) in (1, 2), (nm, value, cps)
        assert all(cp > 0 for cp in cps), (nm, cps)
        assert nm.isascii() and nm.isalnum() and len(nm) <= 255, nm
        if len(cps) == 2:
            assert cps[0] <= 0xFFFF and cps[1] <= 0xFFFF, (nm, cps)
        flags = (1 if 'semi' in e else 0) | (2 if 'legacy' in e else 0)

        if len(cps) == 1 and cps[0] > 0xFFFF:
            aux32.append(cps[0])
            c1, c2 = 0xFFFF, len(aux32) - 1
        elif len(cps) == 1:
            c1, c2 = cps[0], 0
        else:
            c1, c2 = cps[0], cps[1]
        off = len(blob)
        blob += nm.encode('ascii')   # NUL は入れない（off+len で参照）
        rows.append((off, len(nm), flags, c1, c2, nm))

    assert len(aux32) <= 0xFFFF
    assert len(blob) <= 0xFFFF

    with open(out_path, 'w') as f:
        w = f.write
        w("/* GENERATED by tools/gen_entities.py — CPython html.entities "
          "(= WHATWG entities.json 由来)。手編集禁止。 */\n")
        w("#ifndef IFUTO_ENTITIES_GEN_H\n#define IFUTO_ENTITIES_GEN_H\n\n")
        w("typedef struct { u16 name_off; u8 name_len; u8 flags; "
          "u16 cp1; u16 cp2; } IfEntNamed; /* 8 bytes/row */\n")
        w("/* flags: bit0=formal(';'あり), bit1=legacy(裸)。\n")
        w("   cp2==0: 単一 cp。cp1==0xFFFF: astral 単一 cp で本体は IF_ENT_AUX32[cp2]。\n")
        w("   2-cp は両方 BMP 保証（生成時 assert）なので astral と 2-cp は衝突しない。 */\n")
        w("static const u32 IF_ENT_AUX32[%d] = { %s };\n" % (
            len(aux32), ", ".join("0x%Xu" % x for x in aux32)))
        w("static const u8 IF_ENT_NAMES[%u] = {" % len(blob))
        w(", ".join(str(b) for b in blob))
        w("};\n")
        w("static const IfEntNamed IF_ENT_NAMED[%d] = {\n" % len(rows))
        for off, ln, flags, c1, c2, nm in rows:
            w("  {%u,%u,%u,0x%X,0x%X}, /* %s */\n" % (off, ln, flags, c1, c2, nm))
        w("};\n\n")
        w("""/* 完全一致探索: 返り値は index or -1 */
static inline i32 if_ent_find(const char *s, u32 n) {
    i32 lo = 0, hi = (i32)(sizeof IF_ENT_NAMED / sizeof IF_ENT_NAMED[0]) - 1;
    while (lo <= hi) {
        i32 mid = (lo + hi) / 2;
        const IfEntNamed *e = &IF_ENT_NAMED[mid];
        const char *nm = (const char *)IF_ENT_NAMES + e->name_off;
        u32 m = e->name_len < n ? e->name_len : n;
        int c = memcmp(nm, s, m);
        if (c == 0) c = (e->name_len == n) ? 0 : (e->name_len < n ? -1 : 1);
        if (c < 0) lo = mid + 1;
        else if (c > 0) hi = mid - 1;
        else return mid;
    }
    return -1;
}

/* legacy 用: s 前方の legacy 許容エントリで最長名前を探す。
 * 同一 prefix 群はソート上隣接するので、挿入点近傍のごく少数を舐めるだけで足りる */
static inline i32 if_ent_longest_legacy(const char *s, u32 s_len) {
    i32 best = -1;
    u32 best_len = 0;
    i32 lo = 0, hi = (i32)(sizeof IF_ENT_NAMED / sizeof IF_ENT_NAMED[0]);
    while (lo < hi) {
        i32 mid = (lo + hi) / 2;
        const IfEntNamed *e = &IF_ENT_NAMED[mid];
        const char *nm = (const char *)IF_ENT_NAMES + e->name_off;
        if ((int)nm[0] < (int)s[0]) lo = mid + 1;
        else hi = mid;
    }
    /* 第 1 文字が等しい区間だけ走査（平均 ~85 件。全一致はその区間の長さに制限される） */
    for (i32 i = lo; i < (i32)(sizeof IF_ENT_NAMED / sizeof IF_ENT_NAMED[0]); i++) {
        const IfEntNamed *e = &IF_ENT_NAMED[i];
        const char *nm = (const char *)IF_ENT_NAMES + e->name_off;
        if (nm[0] != s[0]) break;
        if (e->name_len <= s_len && (e->flags & 2) && memcmp(nm, s, e->name_len) == 0
            && e->name_len > best_len) {
            best = i;
            best_len = e->name_len;
        }
    }
    return best;
}
#endif
""")

    est = len(blob) + len(rows) * 8 + 4 * len(aux32)
    sys.stderr.write("gen: %d names (blob %d B, rows %d x 8B, aux32 %d, est %.1f KB)\n"
                     % (len(rows), len(blob), len(rows), len(aux32), est / 1024.0))


if __name__ == "__main__":
    main("src/entities_gen.h")
